### ISSUE TITLE
Pedido que se cancela en la pasarela de pago se queda en Pendiente en vez de Cancelado

### ISSUE THREAD

**Issue by edward563** [MagestioEcommerce/redsys-tpv#12]
Los pedidos en los que el cliente llega a la pasarela de pago pero por algún motivo cancela, se deberían poner en un estado de Cancelado pero se ponen en estado Pendiente. 

El pedido aparece en el backend en estado Pendiente sin ninguna información en el Historial de comentarios y tampoco ninguna transacción.

Hay alguna solución para esto?

![image](https://user-images.githubusercontent.com/33431849/103788272-f0053680-503e-11eb-92c8-2578067203cc.png)

**Comment by rondajoaquin** [comment]
Esa funcionalidad está implementada. ¿Puedes realizar la prueba con un Magento 2.3.3 limpio y con la última versión del módulo?

**Comment by edward563** [comment]
Hola Joaquín, gracias por tu respuesta.

Me podrías indicar el fichero en el modulo donde se indica que el pedido se ponga en Cancelado para intentar debugar y ver que pasa.

**Comment by rondajoaquin** [comment]
El archivo es [Magestio\Redsys\Controller\Result\Index](https://github.com/MagestioEcommerce/redsys-tpv/blob/master/app/code/Magestio/Redsys/Controller/Result/Index.php#L167) en la línea 167

**Comment by edward563** [comment]
Hola Joaquin,

He hecho un par de revisiones y me he dado cuenta que si al llegar a la pasarela se hace click en Cancelar si se pone el pedido en Cancelado pero si cierra la ventana con la x o se sale del navegador el pedido se queda en estado Pendiente.

Hay manera de controlar esto?

Gracias

**Comment by rondajoaquin** [comment]
En esta forma de pago mediante redirección a Redsys, no hay manera de controlar que el usuario cierre la ventana o salga del navegador, ya que el módulo espera la respuesta de Redsys para cambiar el estado del pedido.

**Comment by paugnu** [comment]
Hola, 

Esto se soluciona con:
https://github.com/MagestioEcommerce/redsys-tpv/issues/13

Básicamente añadimos un cron para cancelar pedidos que se quedaron «colgados».

**Comment by edward563** [comment]
Hola Pau,

Perfecto, agrego los últimos cambios y doy un feedback.

Muchas gracias y un saludo.

**Comment by edward563** [comment]
Si, con el cron se van cancelando los pedidos que que se quedan en pendiente.
