### ISSUE TITLE
Cancel Pending Orders

### ISSUE THREAD

**Issue by paugnu** [MagestioEcommerce/redsys-tpv#13]
I propose a new functionality:

* Create a new config to set whether pending orders should be automatically cancelled after X minutes
* We will have 2 new fields in conf section:
** Enable/Disable automatic cancellantion
** In case it is enabled, delay time to cancel orders (default: 6h)

This functionality will avoid having pending orders when:
* Customer doesn't cancel the order in the payment gateway
* The payment gateway never provides any feedback

**Comment by rondajoaquin** [comment]
This is great!

Can you create a Pull Request, so we can include your development in the repository?

**Comment by paugnu** [comment]
Yes, I'll do. We're testing the changes the functionality and it seems to work well so far. Default values are not taken into account from the beginning, I need to find out why.

**Comment by paugnu** [comment]
Merged in https://github.com/MagestioEcommerce/redsys-tpv/pull/14
