### ISSUE TITLE
Cart Recovery after Payment Fails

### ISSUE THREAD

**Issue by paugnu** [MagestioEcommerce/redsys-tpv#16]
Hi,

I've found an important issue when:
* It's mandatory to register in checkout
* A customer places an order in checkout, payment fails and returns back to the cart

The expected behavior should be that the order can be place again. However, there are errors when recovering the quote. You can find more information in this comment:
https://github.com/magento/magento2/issues/23908#issuecomment-824133324

I'm going to create a pull request to solve this.

**Comment by rondajoaquin** [comment]
Hi, 

Thank for the Pull Request, but we revert de changes because saw a few errors in de Result/Index.php controller.

**Comment by paugnu** [comment]
Hi @rondajoaquin,

I'm going to create 2 separate two different PR:
* One for fixing the recoverycart (which is the important one)
* One for the invoice point (but I'm trying to see if this change is really necessary after all)
