### ISSUE TITLE
No se muestran los acuerdos de compra en el método de pago

### ISSUE THREAD

**Issue by miquelmauri** [MagestioEcommerce/redsys-tpv#2]
En el método de pago con tarjeta no aparecen las condiciones de uso y compra
<img width="812" alt="captura de pantalla 2018-11-01 a les 20 03 18" src="https://user-images.githubusercontent.com/43760094/47873781-5fa18a80-de12-11e8-84db-e119a7cc753c.png">

mientras que en el resto de métodos si que aparecen.
<img width="815" alt="captura de pantalla 2018-11-01 a les 20 10 34" src="https://user-images.githubusercontent.com/43760094/47873799-6defa680-de12-11e8-948a-7669f13ff4af.png">

**Comment by rondajoaquin** [comment]
El 28 de septiembre actualizamos el archivo: app/code/Magestio/Redsys/view/frontend/web/template/payment/redsys.html para solucionar este problema. ¿Tienes la última versión del módulo?

**Comment by miquelmauri** [comment]
Pues diria que si, pero lo reviso y te comento. Gracias
