### ISSUE TITLE
Pago Correcto pero no envía mail y se queda en pendiente.

### ISSUE THREAD

**Issue by chrisklein00** [MagestioEcommerce/redsys-tpv#23]
Hola!

El pago se realiza correctamente pero el pedido queda en Pendiente y no le llega ningún email de pedido al Cliente. 
¿Nos podéis echar una mano?

Gracias.

**Comment by edward563** [comment]
Hola,

Has comprobado que estén activadas estas 2 opciones en la configuración del método de pago?

![image](https://user-images.githubusercontent.com/33431849/120643311-4b184980-c476-11eb-82e3-e118640f32a3.png)

Un saludo

**Comment by chrisklein00** [comment]
Esta es la configuración que tenemos...

![Captura de pantalla 2021-06-03 a las 14 35 01](https://user-images.githubusercontent.com/16073271/120645723-093cd280-c479-11eb-88f8-cb320aeeed1d.png)

**Comment by rondajoaquin** [comment]
Hola, 
este fallo sólo ocurre con este método de pago o ocurre con otros? 
Aparecen errores en los logs de Magento?

**Comment by chrisklein00** [comment]
Hemos revisado los logs y no vemos nada... Con PayPal el pago entra correctamente, se envía el mail y pasa a Procesando.

**Comment by rondajoaquin** [comment]
Tenéis habilitado otra extensión de pago por Redsys?

**Comment by chrisklein00** [comment]
No, es la única extensión de Redsys que tenemos...

**Comment by rondajoaquin** [comment]
Hola,
Cuando el pedido se queda en pendiente es que la tienda no está recibiendo el callback de Redsys.
¿Puedes comprobar en los logs de acceso al servidor si aparece una petición POST a /redsys/result/index proveniente de Redsys?
Si no aparece, puede ser que el servidor esté bloqueando esa petición, esto es bastante frequente debido al User-Agento de Redsys

**Comment by chrisklein00** [comment]
Si está recibiendo el callback. Si el pedido no está pagado si lo notifica y lo pone en cancelado.

302 GET /redsys/koresult/index/order_id/000000072/?Ds_Sig...

**Comment by rondajoaquin** [comment]
Ese no es el callback, ese es la petición que devuelve el usuario de vuelta a la tienda.
Debes de buscar una petición POST a /redys/result/index

**Comment by chrisklein00** [comment]
No encontramos esa petición... 
![Captura de pantalla 2021-06-04 a las 13 53 48](https://user-images.githubusercontent.com/16073271/120797532-75343f00-c53c-11eb-8d91-04e287ffe699.png)

**Comment by rondajoaquin** [comment]
Entonces, es debido a que el servidor la está bloqueando.
¿Podéis preguntar al suporte del servidor por que la está bloqueando?

**Comment by chrisklein00** [comment]
Vamos a preguntar...

**Comment by chrisklein00** [comment]
Han revisado y que está todo correcto. No encontramos el callback por ningún lado, es como si lo omitiese.

**Comment by chrisklein00** [comment]
Solucionado... Cloudflare con la comprobación de integridad del Navegador bloquea la petición.

Gracias por la ayuda.
