### ISSUE TITLE
No envia emails de confirmación en magento 2.3.3.

### ISSUE THREAD

**Issue by antrax131** [MagestioEcommerce/redsys-tpv#4]
¿Esta versión es compatible con magento 2.3.3?  He hecho una nueva instalación y no envia emails de confirmación en magento 2.3.3.
¿Puede estar relacionado este cambio?
https://community.magento.com/t5/Magento-DevBlog/Backward-incompatible-Changes-in-the-Mail-Library-for-Magento-2/ba-p/144787

**Comment by antrax131** [comment]
[2020-01-03 01:30:37] redsys_logger.CRITICAL: Magento\Framework\Exception\RuntimeException: Type Error occurred when creating object: Magento\Email\Model\Transport\Interceptor in /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:124
Stack trace:
#0 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Email\\M...', Array)
#1 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Email\\M...', Array)
#2 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Mail/TransportInterfaceFactory.php(53): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#3 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(338): Magento\Framework\Mail\TransportInterfaceFactory->create(Array)
#4 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magento/Framework/Mail/Template/TransportBuilder/Interceptor.php(154): Magento\Framework\Mail\Template\TransportBuilder->getTransport()
#5 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(74): Magento\Framework\Mail\Template\TransportBuilder\Interceptor->getTransport()
#6 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-sales/Model/Order/Email/NotifySender.php(37): Magento\Sales\Model\Order\Email\SenderBuilder->send()
#7 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-sales/Model/Order/Email/Sender/OrderCommentSender.php(86): Magento\Sales\Model\Order\Email\NotifySender->checkAndSend(Object(Magento\Sales\Model\Order\Interceptor), true)
#8 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-sales/Model/Service/OrderService.php(146): Magento\Sales\Model\Order\Email\Sender\OrderCommentSender->send(Object(Magento\Sales\Model\Order\Interceptor), true, 'A petici\xC3\xB3n del...')
#9 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(50): Magento\Sales\Model\Service\OrderService->addComment('702', Object(Magento\Sales\Model\Order\Status\History))
#10 /var/www/vhosts/lolatoys.com/httpdocs/app/code/Magestio/Redsys/Helper/Helper.php(149): Magento\Sales\Model\Service\OrderService\Interceptor->addComment('702', Object(Magento\Sales\Model\Order\Status\History))
#11 /var/www/vhosts/lolatoys.com/httpdocs/app/code/Magestio/Redsys/Helper/Helper.php(129): Magestio\Redsys\Helper\Helper->addOrderComment(Object(Magento\Sales\Model\Order\Interceptor), 'A petici\xC3\xB3n del...', 'canceled')
#12 /var/www/vhosts/lolatoys.com/httpdocs/app/code/Magestio/Redsys/Controller/Result/Index.php(157): Magestio\Redsys\Helper\Helper->cancelOrder(Object(Magento\Sales\Model\Order\Interceptor), 'A petici\xC3\xB3n del...')
#13 /var/www/vhosts/lolatoys.com/httpdocs/app/code/Magestio/Redsys/Controller/Result/Index.php(126): Magestio\Redsys\Controller\Result\Index->process()
#14 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magestio/Redsys/Controller/Result/Index/Interceptor.php(24): Magestio\Redsys\Controller\Result\Index->execute()
#15 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/Action/Action.php(108): Magestio\Redsys\Controller\Result\Index\Interceptor->execute()
#16 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magestio\Redsys\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#18 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magestio\Redsys\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magestio/Redsys/Controller/Result/Index/Interceptor.php(65): Magestio\Redsys\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/FrontController.php(159): Magestio\Redsys\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/FrontController.php(98): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magestio\Redsys\Controller\Result\Index\Interceptor))
#22 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#30 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/Http.php(137): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#32 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http\Interceptor->launch()
#33 /var/www/vhosts/lolatoys.com/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#34 {main} [] []

**Comment by chdzma** [comment]
Se ha podido solucionar este problema? aun existe en la versión 2.3.5

**Comment by paugnu** [comment]
Hola,

Yo no he podido reproducir este problema. Ni en Magento 2.3.4 ni en 2.4. El error que se indica es algo genérico que puede estar relacionado con otros puntos no referentes al módulo de redsys.
